INFO 2025-04-28 15:03:14,392 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 15:03:14,945 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 15:03:22,560 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 15:03:22,774 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 15:03:28,062 basehttp "GET / HTTP/1.1" 200 3528
INFO 2025-04-28 15:03:28,366 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 304 0
INFO 2025-04-28 15:37:23,267 basehttp "GET /blog/create/ HTTP/1.1" 302 0
INFO 2025-04-28 15:37:23,283 basehttp "GET /login/?next=/blog/create/ HTTP/1.1" 200 3880
INFO 2025-04-28 15:37:35,853 basehttp "POST /login/?next=/blog/create/ HTTP/1.1" 302 0
INFO 2025-04-28 15:37:35,858 basehttp "GET / HTTP/1.1" 200 3790
INFO 2025-04-28 15:37:40,655 basehttp "GET /blog/ HTTP/1.1" 200 7576
INFO 2025-04-28 15:37:41,805 basehttp "GET /blog/delete/ HTTP/1.1" 200 3333
INFO 2025-04-28 15:37:45,802 basehttp "POST /blog/delete/ HTTP/1.1" 302 0
INFO 2025-04-28 15:37:45,809 basehttp "GET /blog/delete/ HTTP/1.1" 200 3677
INFO 2025-04-28 15:37:59,281 basehttp "POST /blog/delete/ HTTP/1.1" 302 0
INFO 2025-04-28 15:37:59,287 basehttp "GET /blog/delete/ HTTP/1.1" 200 3678
INFO 2025-04-28 15:48:01,361 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:49:36,431 autoreload Watching for file changes with StatReloader
ERROR 2025-04-28 16:49:37,829 exception Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:49:37,833 log Bad Request: /
WARNING 2025-04-28 16:49:37,834 basehttp "GET / HTTP/1.1" 400 143
ERROR 2025-04-28 16:49:42,248 exception Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:49:42,249 log Bad Request: /favicon.ico
WARNING 2025-04-28 16:49:42,249 basehttp "GET /favicon.ico HTTP/1.1" 400 143
INFO 2025-04-28 16:49:55,780 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:49:56,018 autoreload Watching for file changes with StatReloader
ERROR 2025-04-28 16:49:57,457 exception Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:49:57,458 log Bad Request: /
WARNING 2025-04-28 16:49:57,458 basehttp "GET / HTTP/1.1" 400 143
ERROR 2025-04-28 16:49:57,752 exception Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:49:57,753 log Bad Request: /favicon.ico
WARNING 2025-04-28 16:49:57,753 basehttp "GET /favicon.ico HTTP/1.1" 400 143
ERROR 2025-04-28 16:49:59,257 exception Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:49:59,258 log Bad Request: /
WARNING 2025-04-28 16:49:59,259 basehttp "GET / HTTP/1.1" 400 143
ERROR 2025-04-28 16:49:59,513 exception Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8002'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:49:59,514 log Bad Request: /favicon.ico
WARNING 2025-04-28 16:49:59,514 basehttp "GET /favicon.ico HTTP/1.1" 400 143
INFO 2025-04-28 16:50:05,303 autoreload Watching for file changes with StatReloader
ERROR 2025-04-28 16:50:07,387 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:50:07,389 log Bad Request: /
WARNING 2025-04-28 16:50:07,390 basehttp "GET / HTTP/1.1" 400 143
ERROR 2025-04-28 16:50:19,978 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:50:19,979 log Bad Request: /
WARNING 2025-04-28 16:50:19,979 basehttp "GET / HTTP/1.1" 400 143
ERROR 2025-04-28 16:50:20,590 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:50:20,591 log Bad Request: /
WARNING 2025-04-28 16:50:20,591 basehttp "GET / HTTP/1.1" 400 143
ERROR 2025-04-28 16:50:36,414 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:50:36,415 log Bad Request: /
WARNING 2025-04-28 16:50:36,415 basehttp "GET / HTTP/1.1" 400 143
ERROR 2025-04-28 16:50:36,849 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/.venv/lib/python3.12/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-04-28 16:50:36,850 log Bad Request: /favicon.ico
WARNING 2025-04-28 16:50:36,850 basehttp "GET /favicon.ico HTTP/1.1" 400 143
INFO 2025-04-28 16:51:33,931 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:51:34,140 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:51:38,831 basehttp "GET / HTTP/1.1" 200 3528
WARNING 2025-04-28 16:51:38,869 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:51:38,869 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:51:38,870 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:51:38,870 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:51:38,871 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:38,871 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:51:38,871 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:38,872 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:38,872 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:38,872 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:38,997 log Not Found: /favicon.ico
WARNING 2025-04-28 16:51:38,998 basehttp "GET /favicon.ico HTTP/1.1" 404 179
INFO 2025-04-28 16:51:48,008 basehttp "GET /blog/ HTTP/1.1" 200 6969
WARNING 2025-04-28 16:51:48,039 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:51:48,039 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:48,045 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:51:48,046 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:51:48,046 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:48,048 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:51:48,049 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:48,049 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:48,049 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:51:48,050 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
INFO 2025-04-28 16:51:51,217 basehttp "GET /login/ HTTP/1.1" 200 3880
WARNING 2025-04-28 16:51:51,240 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:51:51,241 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:51,254 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:51:51,255 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:51:51,256 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:51,256 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:51,268 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:51:51,269 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:51:51,269 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:51,269 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
INFO 2025-04-28 16:51:57,837 basehttp "POST /login/ HTTP/1.1" 302 0
INFO 2025-04-28 16:51:57,843 basehttp "GET / HTTP/1.1" 200 3790
WARNING 2025-04-28 16:51:57,909 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:51:57,910 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:57,928 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:51:57,928 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:57,949 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:51:57,951 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:51:57,950 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:51:57,951 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:57,952 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:57,953 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
INFO 2025-04-28 16:51:59,566 basehttp "GET /blog/create/ HTTP/1.1" 200 3544
WARNING 2025-04-28 16:51:59,603 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:51:59,603 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:59,618 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:51:59,619 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:51:59,619 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:51:59,620 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:51:59,620 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:59,620 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:59,620 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:51:59,621 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
INFO 2025-04-28 16:52:03,914 basehttp "GET / HTTP/1.1" 200 3446
WARNING 2025-04-28 16:52:03,950 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:52:03,950 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:03,971 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:52:03,972 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:52:03,973 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:52:03,974 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:52:03,974 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:03,974 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:03,975 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:03,975 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
INFO 2025-04-28 16:52:05,145 basehttp "GET /logout/ HTTP/1.1" 302 0
INFO 2025-04-28 16:52:05,149 basehttp "GET /login/ HTTP/1.1" 200 4221
WARNING 2025-04-28 16:52:05,213 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:52:05,213 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:05,226 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:52:05,227 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:52:05,228 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:52:05,228 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:05,228 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:05,229 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:52:05,243 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:52:05,244 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
INFO 2025-04-28 16:53:09,800 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:53:10,159 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:53:11,033 basehttp "GET /login/ HTTP/1.1" 200 3880
WARNING 2025-04-28 16:53:11,077 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:53:11,077 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:11,080 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:53:11,082 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:53:11,084 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:53:11,086 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:53:11,086 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:11,086 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:11,086 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:11,087 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
INFO 2025-04-28 16:53:41,524 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:53:41,751 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:53:42,768 basehttp "GET /login/ HTTP/1.1" 200 3880
WARNING 2025-04-28 16:53:42,804 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:53:42,805 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:53:42,806 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:53:42,806 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:53:42,807 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:53:42,807 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:42,807 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:42,808 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:42,808 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:53:42,808 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
INFO 2025-04-28 16:54:17,096 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:55:35,060 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:56:24,818 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:56:26,314 basehttp "GET / HTTP/1.1" 200 3446
WARNING 2025-04-28 16:56:26,681 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:56:26,682 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
INFO 2025-04-28 16:56:31,910 basehttp "GET /logout/ HTTP/1.1" 302 0
INFO 2025-04-28 16:56:31,918 basehttp "GET /login/ HTTP/1.1" 200 4221
WARNING 2025-04-28 16:56:32,171 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:56:32,171 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
INFO 2025-04-28 16:56:41,175 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:56:41,482 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:56:44,454 basehttp "GET /login/ HTTP/1.1" 200 3880
WARNING 2025-04-28 16:56:44,499 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:56:44,500 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
INFO 2025-04-28 16:57:04,782 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 16:57:05,006 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:58:13,809 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 16:58:20,199 basehttp "GET / HTTP/1.1" 200 3528
WARNING 2025-04-28 16:58:20,272 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:58:20,273 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:58:20,275 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:20,275 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:58:20,275 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:20,276 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:58:20,277 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:20,277 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:20,278 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:58:20,279 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:20,579 log Not Found: /favicon.ico
WARNING 2025-04-28 16:58:20,579 basehttp "GET /favicon.ico HTTP/1.1" 404 179
INFO 2025-04-28 16:58:22,105 basehttp "GET /login/ HTTP/1.1" 200 3880
WARNING 2025-04-28 16:58:22,148 log Not Found: /static/blog/index.css
WARNING 2025-04-28 16:58:22,149 basehttp "GET /static/blog/index.css HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:22,170 log Not Found: /static/velo_validation/jquery.validate.js
WARNING 2025-04-28 16:58:22,174 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:22,171 log Not Found: /static/velo_validation/style.css
WARNING 2025-04-28 16:58:22,172 log Not Found: /static/velo_validation/jquery.js
WARNING 2025-04-28 16:58:22,174 log Not Found: /static/velo_validation/validation.js
WARNING 2025-04-28 16:58:22,175 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:22,175 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 404 179
WARNING 2025-04-28 16:58:22,174 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 404 179
INFO 2025-04-28 17:02:03,272 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:02:03,495 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:02:06,638 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:02:06,847 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:03:22,366 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:03:22,590 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:04:08,918 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:04:09,166 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:04:32,594 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:05:18,013 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:05:18,226 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:05:37,866 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:05:39,760 basehttp "GET / HTTP/1.1" 200 3528
INFO 2025-04-28 17:05:40,181 basehttp "GET /static/blog/index.css HTTP/1.1" 200 819
INFO 2025-04-28 17:05:40,211 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 200 828
INFO 2025-04-28 17:05:40,216 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 200 49431
INFO 2025-04-28 17:05:40,212 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 200 97180
INFO 2025-04-28 17:05:40,244 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 200 35505
WARNING 2025-04-28 17:05:44,331 log Not Found: /favicon.ico
WARNING 2025-04-28 17:05:44,332 basehttp "GET /favicon.ico HTTP/1.1" 404 179
INFO 2025-04-28 17:05:45,468 basehttp "GET /login/ HTTP/1.1" 200 3880
INFO 2025-04-28 17:06:01,216 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:06:03,686 basehttp "GET / HTTP/1.1" 200 3528
INFO 2025-04-28 17:06:03,721 basehttp "GET /static/velo_validation/style.css HTTP/1.1" 200 828
INFO 2025-04-28 17:06:03,722 basehttp "GET /static/blog/index.css HTTP/1.1" 200 819
INFO 2025-04-28 17:06:03,723 basehttp "GET /static/velo_validation/jquery.validate.js HTTP/1.1" 200 49431
INFO 2025-04-28 17:06:03,723 basehttp "GET /static/velo_validation/validation.js HTTP/1.1" 200 35505
INFO 2025-04-28 17:06:03,723 basehttp "GET /static/velo_validation/jquery.js HTTP/1.1" 200 97180
INFO 2025-04-28 17:06:07,289 basehttp "GET /login/ HTTP/1.1" 200 3880
INFO 2025-04-28 17:13:00,736 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:13:01,104 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:14:53,880 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:14:54,099 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:24:58,303 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:35:38,421 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
INFO 2025-04-28 17:35:38,880 autoreload Watching for file changes with StatReloader
INFO 2025-04-28 17:37:56,237 autoreload /home/saksham/Desktop/Velocity Training/Python Training/Day 3/blogs-app/blogs_app/blogs_app/settings.py changed, reloading.
